---
name: CI

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [main]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v8

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go test -v ./...

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: raven-actions/actionlint@v2

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [golangci-lint, test, actionlint]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
